### ISSUE TITLE
[FEAT]: Enhanced Footer

### ISSUE THREAD

**Issue by JiyaGupta-cs** [1010varun/qr-convertor#10]
The current footer looks like this

![image](https://github.com/1010varun/qr-convertor/assets/140608790/bd00baf0-3a85-4450-959f-fb7e039d575e)

I want to create a beautiful footer with animations in it which would make the website look attractive.

**Comment by JiyaGupta-cs** [comment]
@1010varun Please assign me this issue under IWOC

**Comment by JiyaGupta-cs** [comment]
Please add labels of "iwoc2024" and "medium"/"hard" to this issue.

**Comment by Shubhipandey21** [comment]
Please assign me this issue under IWOC @1010varun

**Comment by 1010varun** [comment]
@JiyaGupta-cs this is not that difficult for medium or hard tags.

**Comment by JiyaGupta-cs** [comment]
@1010varun I have fixed it now and It is ready for merge
