### ISSUE TITLE
[FEATURE]: Colored QR

### ISSUE THREAD

**Issue by JiyaGupta-cs** [1010varun/qr-convertor#11]
![image](https://github.com/1010varun/qr-convertor/assets/140608790/6478eaf1-0bc4-4170-b34f-228c69ae2178)
QRs should be creative with colors
QR Codes don’t have to be black and white, they can be made attractive with complementing colors.

**Comment by JiyaGupta-cs** [comment]
@1010varun Please assign this issue to me under IWOC

**Comment by JiyaGupta-cs** [comment]
Please add labels of "iwoc2024" and "medium"/"hard" to this issue.

**Comment by 1010varun** [comment]
@JiyaGupta-cs looks interesting to me, also make it dynamic (ie) the user can choose the color.

**Comment by shresthashim** [comment]
@1010varun please assign this issue to me
