### ISSUE TITLE
[BUG] Limit the amount of characters users can input

### ISSUE THREAD

**Issue by Nemesis-AS** [1010varun/qr-convertor#17]
Currently there is no limit on the amount of characters the user can input, but a QR Code can contain only a certain amount of information. There should be a limit on the amount of characters that the user can enter.

**Comment by Nemesis-AS** [comment]
@1010varun I would like to work on this issue under IWOC24

**Comment by 1010varun** [comment]
@Nemesis-AS assigning it to you go ahead
