### ISSUE TITLE
Enhance Toggle Button for Improved User Interaction

### ISSUE THREAD

**Issue by Tholkappiar** [1010varun/qr-convertor#18]
### Issue Title:
Enhance Toggle Button for Improved User Interaction

### Description:
I noticed that the current toggle button could benefit from improvement to enhance user interaction and overall usability. I'd like to take on this task and propose updates to the toggle button.

### Proposed Changes:
- Replace the existing toggle button with a more interactive alternative.
- Adjust CSS styles for the new toggle button's appearance.
- Update logical function to handle the new toggle button.

### Benefits:
- Improved user experience.
- Enhanced interactivity for a more user-friendly interface.

**Comment by hemant933** [comment]
plz assign it to me

**Comment by 1010varun** [comment]
@hemant933 which button you are talking about??

**Comment by 1010varun** [comment]
@Tholkappiar go on with it

**Comment by 1010varun** [comment]
@Tholkappiar any Update??

**Comment by Tholkappiar** [comment]
yeah almost complete , will push the code !
