### ISSUE TITLE
Implement Persistent Dark Mode State

### ISSUE THREAD

**Issue by TheDarkW3b** [1010varun/qr-convertor#19]
**Issue Summary**:
Currently, the dark mode functionality on the page is not persistent, meaning that when users navigate away or refresh the page, the dark mode state is not saved. This results in users having to manually enable dark mode each time they visit the site.

https://github.com/1010varun/qr-convertor/assets/54339318/31eb27b3-9c96-4e89-a7f3-33fa83604a71

---
**Expected Behavior**:
Dark mode settings should persist across page reloads and navigation, providing users with a consistent experience based on their preference. Once users enable dark mode, the system should save and maintain this state until they choose to disable it.

**Actual Behavior**:
Dark mode settings are not saved, and the page reverts to the default mode after navigation or refresh.

**PS: Assign me this issue under `iwoc2024`**
---

**Comment by 1010varun** [comment]
@TheDarkW3b go ahead assigning it to you

**Comment by 1010varun** [comment]
Fixed in PR #20
