### ISSUE TITLE
Fix footer

### ISSUE THREAD

**Issue by 1010varun** [1010varun/qr-convertor#25]
![Screenshot_2024-01-17-02-22-15-52_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/1010varun/qr-convertor/assets/104075461/3cac2dcd-3981-47db-84ff-83d553f30242)

Fix this overlapping footer to QR.

**Comment by JiyaGupta-cs** [comment]
@1010varun Please assign me this issue under IWOC

**Comment by 1010varun** [comment]
@JiyaGupta-cs 
assigning it to you
