### ISSUE TITLE
Frontend revamp

### ISSUE THREAD

**Issue by 1010varun** [1010varun/qr-convertor#28]
Currently, the UI of this project is not that attractive, although all the components on the page are good their alignment is not.
This issue focuses on making the UI good and attractive.

![image](https://github.com/1010varun/qr-convertor/assets/104075461/7ea32693-b378-42d1-ad5e-5171795741e9)
Current UI

before get assign for this issue prepare a attractive UI.

**Comment by JiyaGupta-cs** [comment]
@1010varun Please assign me this issue under IWOC

**Comment by 1010varun** [comment]
![image](https://github.com/1010varun/qr-convertor/assets/104075461/e36baa5e-d787-40e8-9e8e-f79b88d3859e)
correct the footer
