### ISSUE TITLE
Feature: Download generated QR

### ISSUE THREAD

**Issue by 1010varun** [1010varun/qr-convertor#9]
### Feature Description:
Add a functionality to download the generated QR code by incorporating a user-friendly "Download" button within the application's interface.

### Why is this feature needed?
Currently, users need to take additional steps to save the generated QR code, which might not be as intuitive for some users. Adding a "Download" button directly on the interface enhances user experience and simplifies the process of saving the QR code to local devices.

### Additional Context:
This feature would improve the overall usability of the Text-to-QR Converter, making it more convenient for users to save and share the generated QR codes effortlessly. The "Download" button should trigger the download of the QR code image in a common image format (e.g., PNG or JPEG).

**Comment by JiyaGupta-cs** [comment]
@1010varun Please assign this issue to me
